
import streamlit as st
import pandas as pd
import joblib
import os
from huggingface_hub import hf_hub_download
from google.colab import userdata # Import userdata for Colab secrets

# Streamlit App Layout must be the first Streamlit command
st.set_page_config(page_title="Tourism Package Predictor", layout="centered")

# Define the model repository ID
MODEL_REPO_ID = "MadhaviSura/tourism-prediction-pipeline"
MODEL_FILENAME = "best_tourism_predictor.joblib"

# Get HF_TOKEN from Colab secrets or environment variable
HUGGING_FACE_TOKEN = os.getenv("HF_TOKEN", userdata.get("HF_TOKEN", None))

# Function to download and load the model from Hugging Face Hub
@st.cache_resource
def load_model_from_hf():
    try:
        model_path = hf_hub_download(
            repo_id=MODEL_REPO_ID,
            filename=MODEL_FILENAME,
            repo_type="model",
            token=HUGGING_FACE_TOKEN
        )
        model = joblib.load(model_path)
        st.success(f"Model '{MODEL_FILENAME}' loaded successfully from Hugging Face Hub.")
        return model
    except Exception as e:
        st.error(f"Error loading model from Hugging Face Hub: {e}")
        st.stop() # Stop the app if model loading fails

# Load the model once when the app starts
model = load_model_from_hf()

# Define the final feature columns that the model expects
# This list must EXACTLY match the order and names of features generated by prep.py
# Corrected based on the 'feature_names mismatch' error traceback
FINAL_FEATURE_COLUMNS = [
    'CityTier', 'DurationOfPitch', 'NumberOfPersonVisiting', 'NumberOfFollowups',
    'PreferredPropertyStar', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
    'OwnCar', 'NumberOfChildrenVisiting', 'MonthlyIncome', 'IncomePerPerson',
    'HasChildren', 'IsMajorCity', 'PitchEffectiveness',
    'TypeofContact_Company Invited', 'TypeofContact_Self Enquiry',
    'Occupation_Free Lancer', 'Occupation_Large Business', 'Occupation_Salaried', 'Occupation_Small Business',
    'Gender_Female', 'Gender_Male',
    'ProductPitched_Basic', 'ProductPitched_Deluxe', 'ProductPitched_King', 'ProductPitched_Standard', 'ProductPitched_Super Deluxe',
    'MaritalStatus_Divorced', 'MaritalStatus_Married', 'MaritalStatus_Single',
    'Designation_AVP', 'Designation_Executive', 'Designation_Manager', 'Designation_Senior Manager', 'Designation_VP'
]

st.title("🌴 Tourism Package Purchase Predictor")
st.markdown("Enter customer details to predict if they will purchase the Wellness Tourism Package.")

st.header("Customer Details")

# Input fields arranged in a single column for a centered appearance
age = st.slider("Age", 18, 80, 30)
city_tier = st.selectbox("City Tier", [1, 2, 3], index=0)
duration_of_pitch = st.slider("Duration of Pitch (minutes)", 5, 60, 15)
monthly_income = st.number_input("Monthly Income", min_value=0.0, value=50000.0, step=1000.0)
number_of_followups = st.slider("Number of Follow-ups", 0, 10, 3)
number_of_person_visiting = st.slider("Number of Persons Visiting", 1, 10, 2)
number_of_trips = st.slider("Number of Trips Annually", 0, 20, 5)
pitch_satisfaction_score = st.slider("Pitch Satisfaction Score", 1, 5, 3)
preferred_property_star = st.slider("Preferred Property Star", 1, 5, 3)
passport = st.checkbox("Has Passport")
own_car = st.checkbox("Owns Car")
number_of_children_visiting = st.slider("Number of Children Visiting", 0, 5, 0)

# Corrected categorical options based on model expectations from error message
designation = st.selectbox("Designation", ['AVP', 'Executive', 'Manager', 'Senior Manager', 'VP'], index=1) # Adjusted index
gender = st.selectbox("Gender", ['Male', 'Female'], index=0)
marital_status = st.selectbox("Marital Status", ['Single', 'Married', 'Divorced'], index=0)
occupation = st.selectbox("Occupation", ['Salaried', 'Free Lancer', 'Small Business', 'Large Business'], index=0) # Corrected 'Freelancer' to 'Free Lancer', added 'Large Business'
product_pitched = st.selectbox("Product Pitched", ['Basic', 'Deluxe', 'King', 'Standard', 'Super Deluxe'], index=3) # Corrected 'Platinum' to 'King'
type_of_contact = st.selectbox("Type of Contact", ['Company Invited', 'Self Enquiry'], index=0) # Corrected 'Self Inquiry' to 'Self Enquiry'

# Prediction function
def predict_purchase(
    age, city_tier, duration_of_pitch, monthly_income,
    number_of_followups, number_of_person_visiting,
    number_of_trips, pitch_satisfaction_score,
    preferred_property_star, passport, own_car,
    number_of_children_visiting, designation, gender,
    marital_status, occupation, product_pitched, type_of_contact
):
    # Initialize all final feature columns to 0.0
    input_data = {col: 0.0 for col in FINAL_FEATURE_COLUMNS}

    # Fill in numerical features
    input_data['CityTier'] = float(city_tier)
    input_data['DurationOfPitch'] = float(duration_of_pitch)
    input_data['MonthlyIncome'] = float(monthly_income)
    input_data['NumberOfFollowups'] = float(number_of_followups)
    input_data['NumberOfPersonVisiting'] = float(number_of_person_visiting)
    input_data['NumberOfTrips'] = float(number_of_trips)
    input_data['PitchSatisfactionScore'] = float(pitch_satisfaction_score)
    input_data['PreferredPropertyStar'] = float(preferred_property_star)
    input_data['Passport'] = 1.0 if passport else 0.0
    input_data['OwnCar'] = 1.0 if own_car else 0.0
    input_data['NumberOfChildrenVisiting'] = float(number_of_children_visiting)

    # --- Feature Engineering (consistent with prep.py) ---
    input_data['IncomePerPerson'] = monthly_income / (number_of_person_visiting if number_of_person_visiting > 0 else 1)
    input_data['HasChildren'] = 1.0 if number_of_children_visiting > 0 else 0.0
    input_data['IsMajorCity'] = 1.0 if city_tier == 1 else 0.0
    input_data['PitchEffectiveness'] = pitch_satisfaction_score / (number_of_followups if number_of_followups > 0 else 1)

    # --- One-Hot Encoding Categorical Features ---
    # Ensure mapping matches the exact feature names from model training
    if f'Designation_{designation}' in input_data: input_data[f'Designation_{designation}'] = 1.0
    if f'Gender_{gender}' in input_data: input_data[f'Gender_{gender}'] = 1.0
    if f'MaritalStatus_{marital_status}' in input_data: input_data[f'MaritalStatus_{marital_status}'] = 1.0
    if f'Occupation_{occupation}' in input_data: input_data[f'Occupation_{occupation}'] = 1.0
    if f'ProductPitched_{product_pitched}' in input_data: input_data[f'ProductPitched_{product_pitched}'] = 1.0
    # Correcting for the specific name 'Self Enquiry' as per error
    if type_of_contact == 'Company Invited':
        input_data['TypeofContact_Company Invited'] = 1.0
    elif type_of_contact == 'Self Enquiry':
        input_data['TypeofContact_Self Enquiry'] = 1.0

    # Removed AgeGroup encoding as it was not present in the model's training features

    # Create a DataFrame from the input data, ensuring correct column order
    input_df = pd.DataFrame([input_data], columns=FINAL_FEATURE_COLUMNS)

    # Make prediction
    prediction = model.predict(input_df)[0]
    prediction_proba = model.predict_proba(input_df)[:, 1][0]

    return prediction, prediction_proba, input_df

# Display results
if st.button("Predict Purchase"):
    prediction, prediction_proba, input_df_processed = predict_purchase(
        age, city_tier, duration_of_pitch, monthly_income,
        number_of_followups, number_of_person_visiting,
        number_of_trips, pitch_satisfaction_score,
        preferred_property_star, passport, own_car,
        number_of_children_visiting, designation, gender,
        marital_status, occupation, product_pitched, type_of_contact
    )

    st.subheader("Prediction Result")
    if prediction == 1:
        st.success(f"The customer is likely to purchase the package! (Probability: {prediction_proba:.2f})")
    else:
        st.info(f"The customer is unlikely to purchase the package. (Probability: {prediction_proba:.2f})")

    st.subheader("Processed Input Data (for verification)")
    st.dataframe(input_df_processed)
